### ISSUE TITLE
Titlebar doesnt become acrylic, instead stays as my windows accent color

### ISSUE THREAD

**Issue by slushieuwu** [PSJahn/blurredwindow#2]
![image](https://github.com/PSJahn/blurredwindow/assets/86991346/d769caf8-8657-4214-a5fa-21fd4127e623)

**Comment by slushieuwu** [comment]
one more thing, it still changes the color of the loading screen while in fullscreen,

**Comment by PSJahn** [comment]
It seems most likely to me that you have this Windows setting enabled:
![image](https://github.com/PSJahn/blurredwindow/assets/66626848/3923adfb-9461-4ffe-a259-bbb957527f72)
(Personalization>Colors)

This is what the window looks like with the setting enabled:
![enabled](https://github.com/PSJahn/blurredwindow/assets/66626848/d9ea8ec7-ab15-406e-8a4e-816ac240da0b)

And this is what it looks like with the setting disabled:
![disabled](https://github.com/PSJahn/blurredwindow/assets/66626848/c24c1123-6021-4345-9e44-767f143ff7a1)

**Comment by slushieuwu** [comment]
is there a way to override it for minecraft only?

**Comment by slushieuwu** [comment]
if not, ill just deal with it, its not too terrible

**Comment by PSJahn** [comment]
> is there a way to override it for minecraft only?

Not possible as to my knowledge.
