### ISSUE TITLE
black background

### ISSUE THREAD

**Issue by slushieuwu** [PSJahn/blurredwindow#6]
![image](https://github.com/PSJahn/blurredwindow/assets/86991346/9f42a02b-4cde-4126-89c2-bba72d3777eb)

https://mclo.gs/LLPUQtA

**Comment by slushieuwu** [comment]
not seeing anything in the log about it, not sure if its the fault of another mod

**Comment by tajemniktv** [comment]
ayo, same thing happens to me, although I'm also using FancyMenu, not sure if it might be incompatible with blurredwindow,
logs for reference: https://mclo.gs/0cNTjRJ

**Comment by PSJahn** [comment]
Could both of you check if the mod works without any of the other ones? If so it's definitely a compatibility issue but it might be hard to sort out which mod it relates to.

**Comment by slushieuwu** [comment]
functions without anything else

**Comment by tajemniktv** [comment]
Could we cross reference the mods? I'm kinda tired rn and so not willing to do that lol
Might do.this in an hour or when the drugs start working 🥴👍🏽

**Comment by PSJahn** [comment]
I mean... with 320 mods its pretty hard to find out which one is causing it so yeah
But if there's anything related to GUI Rendering, so like the fancymenu one it could very well be the cause

**Comment by slushieuwu** [comment]
im not using fancymenu so its probably not the cause
or at least not the only one

**Comment by slushieuwu** [comment]
currently disabling some mods that catch my eye

**Comment by slushieuwu** [comment]
no luck yet

**Comment by tajemniktv** [comment]
I did it in my bed without actually looking at my mod list, but I believe I have those mods, which dman also has 

 [✔] InventoryProfilesNext-fabric-1.21-2.0.1
  [✔] InvMove-1.21-0.8.8-Fabric
  [✔] iris-1.7.3 mc1.21

  [✔] language-reload-1.6.1 1.21
  [✔] libIPN-fabric-1.21-5.0.2
  [✔] lithium-fabric-mc1.21-0.12.7

  [✔] melody_fabric_1.0.10_MC_1.21
  [✔] modelfix-1.21-1.6-fabric
  [✔] modernfix-fabric-5.18.5 mc1.21
  [✔] modmenu-11.0.1
  [✔] mru-0.4.4 1.21

  [✔] no-resource-pack-warnings-1.3.0
  [✔] notenoughanimations-fabric-1.7.4-mc1.21

  [✔] numeralping-1.2.4

  [✔] optigui-2.3.0-beta.2 1.21
  [✔] owo-lib-0.12.10 1.21

  [✔] paginatedadvancements-2.4.2
  [✔] physics-mod-3.0.16-mc-1.21.0-fabric
  [✔] polytone-1.21-2.1.1-fabric
  [✔] PresenceFootsteps-1.10.0 1.21
  [✔] puzzle-1.6.3 1.21

  [✔] reeses_sodium_options-1.7.2 mc1.21
  [✔] Resourcify (1.21 -fabric)-1.4.0

  [✔] Searchables-fabric-1.21-1.0.1
  [✔] show-me-your-skin-1.11.1 1.21
  [✔] skinlayers3d-fabric-1.6.6-mc1.21
  [✔] smoothscroll-2.1.2-1.21
  [✔] sodium-extra-0.5.7 mc1.21
  [✔] sodium-fabric-0.5.11 mc1.21
  [✔] sound-physics-remastered-fabric-1.21-1.4.3
  [✔] Sounds-1.0.1 1.21
  [✔] spark-1.10.73-fabric
  [✔] spu-1.8

  [✔] visuality-0.7.6 1.21

  [✔] worldedit-mod-7.3.4-beta-01

  [✔] YetAnotherConfigLib-3.5.0 1.21-fabric

**Comment by slushieuwu** [comment]
oh

**Comment by slushieuwu** [comment]
![image](https://github.com/PSJahn/blurredwindow/assets/86991346/57c92a05-b3ba-46b2-81d3-339ea83d457a)
one of these

**Comment by tajemniktv** [comment]
Debugify, controlify? 
In your case maybe dark loading screen?

**Comment by slushieuwu** [comment]
likely
thought i tested without but i might have missed

**Comment by PSJahn** [comment]
Very strange. It surprises me a lot that it would be one of those mods, but I guess there's a possibility. Maybe I'll be able to write a pull request to said mod to get it compatible, but we'll have to see about that

**Comment by slushieuwu** [comment]
oh its not dark loading screen

**Comment by slushieuwu** [comment]
![image](https://github.com/PSJahn/blurredwindow/assets/86991346/4bfd1383-c386-4d5c-9362-66f57580582a)

**Comment by slushieuwu** [comment]
its forge early loading screen

**Comment by PSJahn** [comment]
... why is it a forge mod

**Comment by slushieuwu** [comment]
https://modrinth.com/mod/forge-early-loading-screen-fabric

**Comment by slushieuwu** [comment]
it ports the forge loading screen to fabric

**Comment by PSJahn** [comment]
Oh yeah that makes a lot of sense. If the window gets created differently or earlier this would be a cause for its properties not being set correctly

**Comment by slushieuwu** [comment]
theres a better alternative that i used on 20.6 but that hasnt been updated yet so i used this

**Comment by slushieuwu** [comment]
it seems to also f up rrls

**Comment by slushieuwu** [comment]
makes the bar tiny and off to the side

**Comment by tajemniktv** [comment]
That's a shitty situation cuz that means, it my case it's a different mod, although I'm guessing it breaks because of the same mechanism. Damn... Imma look out for GUI mods in my modpack then soonTM

**Comment by slushieuwu** [comment]
making an issue on the github

**Comment by slushieuwu** [comment]
> im my case it's a different mod

i could check for you if youre able to send your full modlist

**Comment by tajemniktv** [comment]
Full modlist is available in the logs I sent earlier, although it is a pretty big pack, especially looking at that it's "vanilla(ish) modded", as in client sided mostly mods (about 400) - Sure, if you're up for it then go for it, although it might be a really mundane task lols

**Comment by slushieuwu** [comment]
> making an issue on the github

https://github.com/Jab125/forge-early-loading-screen/issues/13 issue made

**Comment by tajemniktv** [comment]
Also, not sure if this is the same issue, but alt+tabbing causes minecraft window to blink - like it looks normal for 0.5s and goes black for 0.5s it's literally seizure inducing lol 
Video will be available in like 1-5 minutes: https://youtu.be/Lt5DnW3GQMc

edit: video is up, idk why it's so dim, amd relive sucks and i didn't feel like editing it out too lol, most important are like last 15 seconds or smth

**Comment by slushieuwu** [comment]
thats what fullscreen switching usually looks like

**Comment by slushieuwu** [comment]
but thats not fullscreen

**Comment by slushieuwu** [comment]
weird
do you have any borderless fullscreen mods or similar installed?

**Comment by slushieuwu** [comment]
wait
you have dynamic fps installed iirc, might be that

**Comment by slushieuwu** [comment]
i have a bit of an off-topic preposition for this mod.. im going to make a new issue

**Comment by tajemniktv** [comment]
> wait
you have dynamic fps installed iirc, might be that

Oh yeah, disabling DynamicFPS resolved the flicker issue when alt tabbing, thanks:) (Note to dev: Is there a way to fix this issue, as I often alt tab from minecraft and I kinda don't like having a heater in my room while Im not even fully gaming XD) 
Now off to mundane task to see which mod is causing the black screen lolsie

**Comment by PSJahn** [comment]
Nope, AFAIK this is an issue on their end which I can't fix.
