### ISSUE TITLE
[Suggestion] Compatibility with Cubes WIthout Borders (or other borderless fullscreen mods)

### ISSUE THREAD

**Issue by slushieuwu** [PSJahn/blurredwindow#7]
im not sure of the technicalities of it, but it does mostly work already, with some flickering, although when i focus the window itself it seems to get worse

https://github.com/PSJahn/blurredwindow/assets/86991346/6e7c8d0a-5298-4d64-8788-cd27b176142a

i dont know how fixable this is, or if its just a windows moment and it cant be fixed, but i feel the idea might work

**Comment by slushieuwu** [comment]
hang on.. this flickering is also seen ingame on some effects
possibly CWB is at fault here

**Comment by slushieuwu** [comment]
it seems to only be when both are running together..

**Comment by slushieuwu** [comment]
https://github.com/PSJahn/blurredwindow/assets/86991346/eb86a7f1-d449-4287-9598-8fc2d16c4040

i might go make an issue on their end for this too..
also sorry if this is outside of the scope of this mod :p

**Comment by PSJahn** [comment]
The Window always goes gray when unfocused, this is due to windows and I'm not quite sure if there's a way to fix it as of now. The borderless mod combined probably confuses windows which is why this is happening

**Comment by slushieuwu** [comment]
theres the issue on their end

**Comment by slushieuwu** [comment]
it appears to be a windows issue after all, so its likely not worth trying to fix 

was really hoping for blur while in fullscreen, so i guess thats the end of that wish - unless you can do some weird hackery with an image of the desktop or something of that sort

**Comment by slushieuwu** [comment]
you can close this if you dont end up deciding to fix windows being a doofus :p

**Comment by DmanMC** [comment]
hang on, in the world there are weird artifacts when using this mod and either Cubes Without/With Borders, not sure why this affects ingame

![image](https://github.com/PSJahn/blurredwindow/assets/86991346/299e774d-8edc-40b7-8d68-829044fe7052)

![image](https://github.com/PSJahn/blurredwindow/assets/86991346/955c20af-8ec6-4af9-bbb5-64f460db0ae9)

**Comment by DmanMC** [comment]
https://github.com/Kir-Antipov/cubes-with-borders/issues/3

**Comment by DmanMC** [comment]
ill make a seperate issue for it doing this in windowed mode as its not related to the cwb mods

**Comment by slushieuwu** [comment]
oop didnt mean to close this :p

**Comment by PSJahn** [comment]
As neither I, nor the mod author seem to have an idea on why this issue is occurring, I'll close it for now.
